class StaticData {
  Map<String, dynamic> englishTitles = {
    'jobSeekerSignUp': 'Job Seeker',
    'companySignUp': 'company SignUp',
    'NEXT': 'Next',
    'GetStarted': 'Get Started',
    'SKIP': 'Skip',
    'PREV': 'Previous',
    'login': 'Login',
    'signUp': 'SignUp',
    'createAccount': 'SignIn',
    'Forget Password?': 'Forget Password?',
    'UserName': 'User Name',
    'E_Mail': 'E_Mail',
    'Password': 'Password',
    'Confirm Password': 'Confirm Password',
    'PhoneNumber1': 'Phone Number',
    'ApplicationPolicy': 'Agree For Conditions',
    'Policy': 'Read Policy',
    'haveAccount': 'Have account?',
    'doNotHaveAccount': "Don't have account?",
    'companyInfo': 'Company Information',
    'companyName': 'Company Name',
    'companyCommNo': 'Commercial Registration No',
    'companyWebSite': 'Company WebSite',
    'CompanyOwner': 'Company Owner',
    'CompanyNotes': 'Company Notes',
    'searching': 'Search'
  };
  Map<String, dynamic> arabicTitles = {
    'jobSeekerSignUp': 'باحث عن وظيفه',
    'companySignUp': 'صاحب عمل',
    'NEXT': 'التالي',
    'SKIP': 'تخطي',
    'GetStarted': 'أبدا',
    'PREV': 'السابق',
    'login': 'تسجيل الدخول',
    'signUp': 'أنشاء الحساب',
    'createAccount': 'أنشاء حساب جديد',
    'Forget Password?': 'نسيت كلمة المرور؟',
    'UserName': 'أسم المستخدم',
    'E_Mail': 'البريد الالكتروني',
    'Password': 'كلمة المرور',
    'Confirm Password': 'تأكيد كلمة المرور',
    'PhoneNumber1': 'رقم الهاتف',
    'PhoneNumber2': ' رقم الهاتف الاخر',
    'ApplicationPolicy': 'لقد وافقت علي الشروط',
    'Policy': 'الشروط',
    'haveAccount': 'لدي حساب؟',
    'doNotHaveAccount': ' ليس لدي حساب؟',
    'companyInfo': 'معلومات المنشأه',
    'companyName': 'أسم المنشأه',
    'companyCommNo': 'السجل التجاري للمنشأه',
    'companyWebSite': 'الموقع الالكتروني',
    'CompanyOwner': 'معلومات مالك الشركة',
    'CompanyNotes': 'مزيد عن الشركة',
    'searching': 'بحث'
  };
}
